import './globals.css'

export const metadata = {
  title: 'Yae Miko',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="[&::-webkit-scrollbar]:hidden">{children}</body>
    </html>
  )
}
